### ISSUE TITLE
nav bar buttons hover transition

### ISSUE THREAD

**Issue by franciscobaila** [groupbuddies/2015.cs.groupbuddies.com#12]
![screen shot 2015-05-06 at 18 55 07](https://cloud.githubusercontent.com/assets/6978461/7499737/7d6079e8-f421-11e4-9cda-32f5073c7d77.png)

**Comment by zamith** [comment]
@fcbaila What is this supposed to be?

**Comment by franciscobaila** [comment]
transition to this state when hovered

![screen shot 2015-05-06 at 20 47 41](https://cloud.githubusercontent.com/assets/6978461/7502080/4459e3ea-f431-11e4-8c94-c77524f1f5fb.png)

**Comment by zamith** [comment]
@fcbaila Didn't the color of the navbar change?
