### ISSUE TITLE
Smaller logo top-left

### ISSUE THREAD

**Issue by franciscobaila** [groupbuddies/2015.cs.groupbuddies.com#2]
Move logo to top left on the page with 50px height

**Comment by zamith** [comment]
@fcbaila Care to clarify?

**Comment by franciscobaila** [comment]
https://drive.google.com/file/d/0ByMGE2OmtZkbZExGVjBGTWZtWGs/view?usp=sharing

**Comment by franciscobaila** [comment]
Logo moves to page top-left like in the nav-bar
