### ISSUE TITLE
Update tool icons in "O que vais aprender" section

### ISSUE THREAD

**Issue by franciscobaila** [groupbuddies/2015.cs.groupbuddies.com#20]
![screen shot 2015-05-07 at 15 00 38](https://cloud.githubusercontent.com/assets/6978461/7516882/da8e06c8-f4c9-11e4-837f-aa0036fbcfda.png)

**Comment by franciscobaila** [comment]
https://drive.google.com/folderview?id=0ByMGE2OmtZkbfjEydm90Qm10eEtlMWc3aXp1N2tmb0dKVGxNa0cwWEVVbXBHQnBtSkkyZVk&usp=sharing

**Comment by fcbaila** [comment]
https://drive.google.com/file/d/0ByMGE2OmtZkbYnppaUhYUkxMams/view?usp=sharing

**Comment by fcbaila** [comment]
@zamith
