### ISSUE TITLE
Logo with white letters on footer

### ISSUE THREAD

**Issue by franciscobaila** [groupbuddies/2015.cs.groupbuddies.com#4]
Change logo on footer to logo with white letters

**Comment by fcbaila** [comment]
Change logo on footer to logo with white letters

**Comment by franciscobaila** [comment]
https://drive.google.com/file/d/0ByMGE2OmtZkbZF9wNXBLTlp5ZTg/view?usp=sharing

**Comment by naps62** [comment]
@fcbaila This logo needs to be fixed I think

**Comment by franciscobaila** [comment]
@naps62 true https://drive.google.com/file/d/0ByMGE2OmtZkbY19CNlVkQUIyV28/view?usp=sharing

**Comment by naps62** [comment]
fixed in the next deploy
