### ISSUE TITLE
Header SVGs needs to be fixed

### ISSUE THREAD

**Issue by naps62** [groupbuddies/2015.cs.groupbuddies.com#6]
When optimized through SVGO some artifacts show up

Options:
1. Fix the SVG somehow in Sketch, so that the optimizer doesn't screw with it (I don't know if this is possible)
2. Use a PNG instead
3. Skip SVGO, which is not desirable, since it's reducing the image from 600k to 200k

**Comment by franciscobaila** [comment]
https://drive.google.com/file/d/0ByMGE2OmtZkbMjdRTTdLZFNyVlk/view?usp=sharing

**Comment by naps62** [comment]
Fixed
